### ISSUE TITLE
1.14 Gui Problem

### ISSUE THREAD

**Issue by Blueeyestar** [RypoFalem/ArmorStandEditor#17]
We use the plugin a lot on our server. At the moment we are working on changing to Spigot 1.14.
Unfortunately there is the Gui problem in the 1.14 like with many plugins. 
We would be happy if this is fixed.

[14:45:53] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to ArmorStandEditor v1.13-21
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1183) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1938) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1036) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1031) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.craftbukkit.v1_14_R1.entity.CraftHumanEntity.openCustomInventory(CraftHumanEntity.java:455) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.craftbukkit.v1_14_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:338) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at io.github.rypofalem.armorstandeditor.menu.Menu.openMenu(Menu.java:236) [armorstandeditor-1.13-21.jar:?]
	at io.github.rypofalem.armorstandeditor.PlayerEditor$OpenMenuTask.run(PlayerEditor.java:408) [armorstandeditor-1.13-21.jar:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1005) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:953) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:798) [Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getName()Ljava/lang/String;
	at io.github.rypofalem.armorstandeditor.PlayerEditorManager.onPlayerMenuClose(PlayerEditorManager.java:280) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:311) ~[Spigot-latest.jar:git-Spigot-47463c2-6de3aa1]
	... 18 more

**Comment by RypoFalem** [comment]
Thanks for the report! 

Spigot team removed a method that I used from the Bukkit API. It's fixed now 0d479f6c6b5f570965adf30a68d67f9b0b72fa35. You can download the latest build on Spigot https://www.spigotmc.org/resources/armor-stand-editor.7688/ 

I shouldn't have to say this but obviously the spigot 1.14 build is still in development. I don't recommend using it or the updated plugin for live servers just yet!

**Comment by RypoFalem** [comment]
Gonna go ahead and close this. Nothing like this should crop up again in 1.14 but let me know if it does!
