### ISSUE TITLE
Need to update PlotSquared API

### ISSUE THREAD

**Issue by RoboMWM** [RypoFalem/ArmorStandEditor#4]
Mind updating the PlotSquared hooks?

```
2016-04-09 12:07:31 [INFO] [ArmorStandEditor] Enabling ArmorStandEditor v1.9-0.1.7BETA
2016-04-09 12:07:31 [ERROR] Error occurred while enabling ArmorStandEditor v1.9-0.1.7BETA (Is it up to date?)
java.lang.NoSuchMethodError: com.intellectualcrafters.plot.api.PlotAPI: method <init>()V not found
at io.github.rypofalem.armorstandeditor.protection.PlotSqProtection.<init>(PlotSqProtection.java:19) ~[?:?]
at io.github.rypofalem.armorstandeditor.ArmorStandEditorPlugin.onEnable(ArmorStandEditorPlugin.java:76) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[patched_1.9.2.jar:git-Paper-652]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319) [patched_1.9.2.jar:git-Paper-652]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.9.2.jar:git-Paper-652]
at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:357) [patched_1.9.2.jar:git-Paper-652]
at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:317) [patched_1.9.2.jar:git-Paper-652]
at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:412) [patched_1.9.2.jar:git-Paper-652]
at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:377) [patched_1.9.2.jar:git-Paper-652]
at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [patched_1.9.2.jar:git-Paper-652]
at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:273) [patched_1.9.2.jar:git-Paper-652]
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:571) [patched_1.9.2.jar:git-Paper-652]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_72]
2016-04-09 12:07:31 [INFO] [ArmorStandEditor] Disabling ArmorStandEditor v1.9-0.1.7BETA
```

**Comment by RypoFalem** [comment]
Uploaded a new version on spigot. Let me know if it fixes the issue.

**Comment by RoboMWM** [comment]
Just had time to update today, and unfortunately it hasn't. Using PlotSquared version 3.4.0

```
2016-04-15 18:27:27 [INFO] [ArmorStandEditor] Enabling ArmorStandEditor v1.9-0.1.8BETA
2016-04-15 18:27:27 [ERROR] Error occurred while enabling ArmorStandEditor v1.9-0.1.8BETA (Is it up to date?)
java.lang.NoSuchMethodError: com.intellectualcrafters.plot.api.PlotAPI: method <init>()V not found
    at io.github.rypofalem.armorstandeditor.protection.PlotSqProtection.<init>(PlotSqProtection.java:19) ~[?:?]
    at io.github.rypofalem.armorstandeditor.ArmorStandEditorPlugin.onEnable(ArmorStandEditorPlugin.java:79) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[patched_1.9.2.jar:git-Paper-682]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319) [patched_1.9.2.jar:git-Paper-682]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.9.2.jar:git-Paper-682]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:357) [patched_1.9.2.jar:git-Paper-682]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:317) [patched_1.9.2.jar:git-Paper-682]
    at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:412) [patched_1.9.2.jar:git-Paper-682]
    at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:377) [patched_1.9.2.jar:git-Paper-682]
    at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [patched_1.9.2.jar:git-Paper-682]
    at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:273) [patched_1.9.2.jar:git-Paper-682]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:571) [patched_1.9.2.jar:git-Paper-682]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_72]
```

**Comment by RypoFalem** [comment]
Oh, I tested with plotsquared 3.3.3. I'll see what I can do to make it work with the dev build.

**Comment by RypoFalem** [comment]
Ok fixed for real. Tested with both plotsquared 3.3.3 and 3.3.4

**Comment by RoboMWM** [comment]
Yup, seems to be working now, thanks!
