### ISSUE TITLE
Could not pass event PlayerItemHeldEvent to ArmorStandEditor

### ISSUE THREAD

**Issue by mibby** [RypoFalem/ArmorStandEditor#8]
ArmorStandEditor v1.10.2-0.1.13

Error occurs when shift + scrolling over an empty inventory slot.
```
[12:34:22] [Server thread/ERROR]: Could not pass event PlayerItemHeldEvent to ArmorStandEditor v1.10.2-0.1.13
org.bukkit.event.EventException
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.10.2.jar:git-Paper-916]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.10.2.jar:git-Paper-916]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-916]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-916]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-916]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1135) [patched_1.10.2.jar:git-Paper-916]
	at net.minecraft.server.v1_10_R1.PacketPlayInHeldItemSlot.a(SourceFile:30) [patched_1.10.2.jar:git-Paper-916]
	at net.minecraft.server.v1_10_R1.PacketPlayInHeldItemSlot.a(SourceFile:8) [patched_1.10.2.jar:git-Paper-916]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-916]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-916]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:808) [patched_1.10.2.jar:git-Paper-916]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-916]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [patched_1.10.2.jar:git-Paper-916]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-916]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NullPointerException
	at io.github.rypofalem.armorstandeditor.ArmorStandEditorPlugin.isEditTool(ArmorStandEditorPlugin.java:146) ~[?:?]
	at io.github.rypofalem.armorstandeditor.PlayerEditorManager.onScrollNCrouch(PlayerEditorManager.java:168) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.10.2.jar:git-Paper-916]
	... 16 more
```

Version 1.10.2-0.1.13 doesn't error.

**Comment by RypoFalem** [comment]
Thanks! Fix is made, gonna release update shortly.
